name: Handle Event

on:
  repository_dispatch:
    types:
      - my_custom_event

jobs:
  handle_event:
    runs-on: ubuntu-latest

    steps:
      - name: Log Event
        run: echo "Custom event 'my_custom_event' received!"
